### PR TITLE
Fix default robots overriding

### LINKED ISSUE #727: `dangerouslySetAllPagesToNoIndex` won't be overridden by `noindex: false` in each page
SSIA.

I configured `dangerouslySetAllPagesToNoIndex: true` in `<DefaultSeo>`, then set `noindex: false` in `<NextSeo>` in page component. However, robots are still `noindex,follow`.

### PR DESCRIPTION
**Pull request by yukukotani**
## Description of Change(s):

Fixes #727. 

`dangerouslySetAllPagesToNoIndex` in `<DefaultSeo>` had been having a priority over `noindex: false` in `<NextSeo>` of each page component. `nofollow` is also the same.

Also, the test case have expected wrong result. This PR fixes it.

### CODE REVIEW

**Comment by rolandtoth** [comment]
@Monchi any chance of updating the branch? This fix would be great if could be merged some day.

**Comment by Monchi** [comment]
@rolandtoth Sure. I've updated and published a new patched version.
https://www.npmjs.com/package/next-seo-yuku-fork

**Comment by garmeeh** [comment]
Hey @Monchi, thank you for the contribution 🙏 😄

`next-seo` was just re-written for V5, would you mind double checking your change is expected and updating the conflict.  Apologies about the delay.

**Comment by Monchi** [comment]
@garmeeh Sure, wait a moment!

**Comment by Monchi** [comment]
@garmeeh  I've rebased and checked the behavior. Please take a look.

File: src/meta/buildTags.tsx [hunk 1]
```diff
@@ -119,13 +119,13 @@ const buildTags = (config: BuildTagsParams) => {
   }
 
   const noindex =
-    config.noindex ||
-    defaults.noindex ||
-    config.dangerouslySetAllPagesToNoIndex;
+    config.noindex != null
```
Comment (nyedidikeke) [inline src/meta/buildTags.tsx:122]: `noindex` should be a _boolean_, otherwise _undefined_.

File: src/meta/buildTags.tsx [hunk 2]
```diff
@@ -119,13 +119,13 @@ const buildTags = (config: BuildTagsParams) => {
...
+      ? config.noindex
+      : defaults.noindex || config.dangerouslySetAllPagesToNoIndex;
   const nofollow =
-    config.nofollow ||
-    defaults.nofollow ||
-    config.dangerouslySetAllPagesToNoFollow;
+    config.nofollow != null
```
Comment (nyedidikeke) [inline src/meta/buildTags.tsx:126]: `nofollow` should be a _boolean_, otherwise _undefined_.

File: src/meta/buildTags.tsx (hunk 1 above)
Comment (Monchi) [reply src/meta/buildTags.tsx:122]: @nyedidikeke Sorry, I don't get it. With this code, `noindex` of each page is respected if it's given, otherwise, global `dangerouslySetAllPagesToNoIndex` is reffered.

**Comment by Monchi** [comment]
@garmeeh Ready for review

**Comment by yukukotani** [comment]
@garmeeh  Any news? I think @nyedidikeke's review is not a problem. Any other change requests are welcome.

**Comment by MAfzalKhan1997** [comment]
when this PR will get merged ? I'm facing the same issue and currently on latest version of next-seo

**Comment by garmeeh** [comment]
@yukukotani merged this today and spent a bit of time looking through it. The tests are failing on it. 

The tests were failing on your pull request due to unrelated package issues. I opened an up to date branch pull request here to allow CI to run and tests did fail: https://github.com/garmeeh/next-seo/pull/1194

**Comment by garmeeh** [comment]
While going through remaining pull requests, turns out #1062 had an almost identical change as yours. Tests ended passing on this pull request. I have released this change now. Thanks for all your effort on this and apologies on not so great attention on this one. 

This has been released in v6 now
